name: hello from the github action batch-20
on: null
workflow_dispatch: null
jobs: null
say_hello: null
runs-on: ubuntu-latest
steps:
  - run: echo “hellow from github action workflow” “hellow from github action workflow”
