---
name: Hello from GitHub Actions MACOS
on:
  workflow_dispatch:
jobs:
  say_hello:
    runs-on: macos-latest
    steps:
      - run: echo "Hello from GitHub Actions Workflow MACOS"
say_hello_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from GitHub Actions Workflow ubuntu-latest"
